channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - netcdf4
  - xarray
  - dask
  - ipykernel
  - jupyter_client[version='<8']
  - notebook
  - matplotlib
  - tqdm
  - labelme
  - pyqt
  - pyyaml
  - sqlite
  - dash
  - dash-bootstrap-component
  - scikit-image
prefix: /Users/gaspardringuenet/miniforge3/envs/acoustic-communities
