[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "escore-python"
version = "0.0.0"

[tool.setuptools]
packages = ["escore"]

[tool.setuptools.package-dir]
"" = "."